version: "3.7"
services:
  web-server:
    image: app-web:latest         # использовать собранный образ из Jenkins
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
      - phpmyadmin

  db:
    image: app-db:latest          # использовать собранный образ из Jenkins
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'lena'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: 'db'
      PMA_USER: 'root'
      PMA_PASSWORD: 'secret'
    ports:
      - "5000:80"

volumes:
  mysql-data:
